gen:
	# protoc greet/greetpb/*.proto --go_out=plugins=grpc:.
	protoc greet/greetpb/*.proto --go_out=plugins=grpc:./greet/greetpb/
	protoc greet/greetpb/*.proto --go_out=plugins=grpc:./greet/
	protoc calculator/calculatorpb/*.proto --go_out=plugins=grpc:./calculator/

clean:
	ls -al